// <auto-generated />
using System;
using ConstrutoraDesbravador.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConstrutoraDesbravador.Data.Migrations
{
    [DbContext(typeof(ConstrutoraDesbravadorContext))]
    [Migration("20250123150038_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("RiscoProjeto")
                        .HasColumnType("integer");

                    b.Property<int>("StatusProjeto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Projeto", (string)null);
                });

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.ProjetoFuncionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("integer");

                    b.HasKey("FuncionarioId", "ProjetoId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("ProjetoFuncionarios");
                });

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.Projeto", b =>
                {
                    b.HasOne("ConstrutoraDesbravador.Business.Models.Funcionario", "Responsavel")
                        .WithMany("ProjetosResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.ProjetoFuncionario", b =>
                {
                    b.HasOne("ConstrutoraDesbravador.Business.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .IsRequired();

                    b.HasOne("ConstrutoraDesbravador.Business.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ConstrutoraDesbravador.Business.Models.Funcionario", b =>
                {
                    b.Navigation("ProjetosResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
